/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-11-12 07:59:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views.Admin.container.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/Views/Admin/container/account/insert.jsp", Long.valueOf(1605164439615L));
    _jspx_dependants.put("/Views/Admin/commom/footer.jsp", Long.valueOf(1605069075478L));
    _jspx_dependants.put("/Views/Admin/container/account/delete.jsp", Long.valueOf(1605167766575L));
    _jspx_dependants.put("/Views/Admin/commom/header.jsp", Long.valueOf(1605163700170L));
    _jspx_dependants.put("/Views/Admin/container/account/update.jsp", Long.valueOf(1605166660182L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t");

			String kqQuery = "";
		if (request.getAttribute("hasError") != null)
			kqQuery = (String) request.getAttribute("hasError");
		String kq="";
		if(request.getAttribute("kq")!=null)
				kq=(String) request.getAttribute("kq");
		request.setAttribute("kqInsert", kqQuery);
		
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("--\r\n");
      out.write(" \r\n");
      out.write("do it in .css\r\n");
      out.write(".clearfix::after {\r\n");
      out.write("\tcontent: \" \";\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 	String id1 ="" ; 
		if (request.getAttribute("email") != null) 
			id1 = (String) request.getAttribute("email"); 
      out.write(" \r\n");
      out.write("\t<p style=\"text-align: center;\">-------example header-------</p>\r\n");
      out.write("\t<ul class=\"main-nav\" style=\"list-style: none;\">\r\n");
      out.write("\t\t<li><a href=\"/CuaHang/Views/Admin/container/home.jsp\">Home</a></li>\r\n");
      out.write("\t\t<li><a href=\"/CuaHang/Views/Admin/container/account/account.jsp\">Account</a></li>\r\n");
      out.write("\t\t<li><a href=\"/CuaHang/Views/Admin/container/product.jsp\">Product</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"> [");
      out.print(id1 );
      out.write("] </a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t<p style=\"text-align: center;\">-----------------end header-----------</p>\r\n");
      out.write("\t<div class=\"clearfix\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1>Account Center</h1>\r\n");
      out.write("\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/choose-in-account\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Insert\" name=\"choose\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Update\" name=\"choose\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Delete\" name=\"choose\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");
 if(kq.equals("1")){
      out.write(' ');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"insert\">\r\n");
      out.write("\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/insert-account\"\r\n");
      out.write("\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t<p>Insert</p>\r\n");
      out.write("\t\t\t<table cellspacing=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Email:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"email\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Password</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"pass\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">First name:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"firstname\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Last name:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"lastname\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Phone:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"phone\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Address</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"address\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Gender:</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int sex = 0; sex < 2; sex++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(sex);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (sex == 0) {
								
      out.write("Male");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (sex == 1) {
								
      out.write("Female");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Date of birth:</td>\r\n");
      out.write("\t\t\t\t\t<td>Time Picker Here</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Role:</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"role\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int role = 0; role < 3; role++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(role);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (role == 0) {
								
      out.write("USER");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (role== 1) {
								
      out.write("SALEPERSON");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (role == 2) {
								
      out.write("ADMINISTRATOR");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" value=\"insert\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(' ');
}
		else if(kq.equals("2")) {
      out.write("e\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
String email="";
		if(request.getAttribute("email")!=null)
			 email=(String) request.getAttribute("email");
		
      out.write("\r\n");
      out.write("\t<div class=\"update\">\r\n");
      out.write("\t\t<p>Update</p>\r\n");
      out.write("\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fill-By-Email\"\r\n");
      out.write("\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t<table cellspacing=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\" style=\"padding-left: 44px\">Email:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"email\" value=");
      out.print(email);
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"CheckButton\"><input type=\"submit\" value=\"Check\"\r\n");
      out.write("\t\t\t\t\t\tname=\"Check\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/update-account\"\r\n");
      out.write("\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t<table cellspacing=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Password</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"pass\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">First name:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"firstname\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Last name:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"lastname\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Phone:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"phone\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Address</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"address\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Gender:</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int sex = 0; sex < 2; sex++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(sex);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (sex == 0) {
								
      out.write("Male");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (sex == 1) {
								
      out.write("Female");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Date of birth:</td>\r\n");
      out.write("\t\t\t\t\t<td>Time Picker Here</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Role:</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"role\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int role = 0; role < 3; role++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(role);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (role == 0) {
								
      out.write("USER");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (role == 1) {
								
      out.write("SALEPERSON");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (role == 2) {
								
      out.write("ADMINISTRATOR");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" value=\"update\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(' ');
} 
		else if(kq.equals("3")){
      out.write(' ');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
String error="";
		if(request.getAttribute("hasError")!=null)
			 error=(String) request.getAttribute("hasError");
		
      out.write("\r\n");
      out.write(" <p>delete</p>\r\n");
      out.write(" <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/delete-account\"\r\n");
      out.write("\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t<table cellspacing=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\" style=\"padding-left: 44px\">Email:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"email\" value=");

      out.write("></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"CheckButton\"><input type=\"submit\" value=\"Delete\"\r\n");
      out.write("\t\t\t\t\t\tname=\"Check\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(' ');
} 
      out.write("\r\n");
      out.write("\t\tThong bao: ");
      out.print(kqQuery);
      out.write("!\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<p style=\"text-align: center;\">---------------------------------------------------------------------------------------------------------------------------example footer---------------------------------------------------------------------------------------------------------------------------</p>\r\n");
      out.write("\t<p>United States Copyright © 2020 Apple Inc. All rights reserved.Privacy Policy Terms of Use Sales and Refunds Legal Site Map</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
